# Generated by Django 5.0.6 on 2026-05-07 00:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor total')),
                ('status', models.CharField(choices=[('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='CONCLUIDA', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'vendas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Item de venda',
                'verbose_name_plural': 'Itens de venda',
                'db_table': 'itens_venda',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['-data'], name='vendas_data_d90030_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente'], name='vendas_cliente_bc902f_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='vendas_status_0bb754_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['venda'], name='itens_venda_venda_i_db612c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvenda',
            index=models.Index(fields=['produto'], name='itens_venda_produto_9e3403_idx'),
        ),
    ]
