# Generated by Django 5.0.6 on 2026-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="perfil",
            field=models.CharField(
                choices=[("ADMIN", "Administrador"), ("FUNCIONARIO", "Funcionário")],
                default="FUNCIONARIO",
                max_length=20,
            ),
        ),
    ]
